name <-readline(prompt = "Enter Your Name: ")
roll <-as.numeric(readline(prompt = "Enter Your Roll: "))
age <-as.numeric(readline(prompt = "Enter Your Age: "))
vector <-c(1,2,8,6)
s <- sum(vector)
print(name)
print(roll)
print(age)
print(s)
